# Generated by Django 3.2.8 on 2024-12-03 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='用户头像')),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号码')),
                ('role', models.IntegerField(default=1, verbose_name='角色（0管理员 1普通用户 2老师）')),
                ('status', models.IntegerField(default=0, verbose_name='帐号状态(0正常 1封禁/0上线 1下线)')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'abs_user',
            },
        ),
    ]
