# Generated by Django 4.2.16 on 2024-12-05 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='AbsUserID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('nickname', models.CharField(default='qwe', max_length=16, verbose_name='昵称')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='用户头像')),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号码')),
                ('role', models.IntegerField(verbose_name='角色（0管理员 1普通用户 2演示账号）')),
                ('status', models.IntegerField(default=0, verbose_name='帐号状态(0正常 1封禁)')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱地址')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='TeacherID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('nickname', models.CharField(default='x老师', max_length=16, verbose_name='姓名')),
                ('avatar', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('status', models.IntegerField(default=0, verbose_name='帐号状态(0上架 1下架)')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱地址')),
                ('phonenumber', models.CharField(default='123456', max_length=18, verbose_name='手机号码')),
                ('hprice', models.IntegerField(verbose_name='每小时价格')),
                ('province', models.CharField(max_length=8, verbose_name='省份')),
                ('county', models.CharField(max_length=8, verbose_name='市/区')),
                ('area', models.CharField(max_length=64, null=True, verbose_name='详细地址')),
                ('eq', models.CharField(max_length=15, verbose_name='学历')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
