# Generated by Django 4.2.16 on 2024-12-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='eq',
            field=models.IntegerField(default=3, verbose_name='学历'),
        ),
    ]
