# Generated by Django 3.2.8 on 2024-12-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='AbsUserID'),
        ),
        migrations.AlterField(
            model_name='absuser',
            name='role',
            field=models.IntegerField(verbose_name='角色（0管理员 1普通用户 2老师）'),
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='AbsUserID')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱地址')),
                ('absuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sysuser', to='system.absuser')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
