# Generated by Django 4.2.16 on 2024-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20241203_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='nickname',
            field=models.CharField(default='qwe', max_length=16, verbose_name='昵称'),
        ),
    ]
