# Generated by Django 4.2.16 on 2024-12-09 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_teacher_eq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='AbsUserID')),
                ('teacher_id', models.IntegerField(verbose_name='老师id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('comment', models.TextField(verbose_name='评论')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
