# Generated by Django 4.2.16 on 2024-12-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_sysuser_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absuser',
            old_name='status',
            new_name='is_active',
        ),
    ]
