# Generated by Django 4.2.16 on 2024-12-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_status_absuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='email',
        ),
        migrations.AddField(
            model_name='absuser',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱地址'),
        ),
    ]
