# Generated by Django 4.2.16 on 2024-12-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_remove_sysuser_nickname_absuser_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absuser',
            old_name='is_active',
            new_name='status',
        ),
    ]
